name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with: 
          bundler-cache: true
      - name: run rubocop
        run: bundle exec rubocop
  
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with: 
          bundler-cache: true
      - name: run brakeman
        run: bundle exec brakeman

  bundler_audit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with: 
          bundler-cache: true
      - name: run bundler-audit
        run: bundle exec bundler-audit

  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_USER: test
          POSTGRES_PASSWORD: 123456
        ports: 
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with: 
          bundler-cache: true
      - name: Run rspec
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://test:123456@localhost:5432/rails_expense_workflow_test
        run: |
          bin/rails db:prepare
          bundle exec rspec